"use client";

import { useMemo } from "react";
import type { GameRow } from "@/lib/useGame";
import { recomputeResult, sideLabel } from "@/lib/fair";
import { useWallet } from "@/lib/wallet";

// Plain-language explanations of each cryptographic input, for non-technical players.
const TIPS: Record<string, string> = {
  prevrandao:
    "Ethereum Network Entropy: A random number generated by the blockchain itself. Totally out of the casino's or player's control.",
  player:
    "Your Wallet Address: Proves this specific coin flip belongs uniquely to your cryptographic identity.",
  seed:
    "Your Custom Seed: Entropy you generated when clicking. Proves the casino couldn't predict your action and cheat.",
  nonce:
    "Your Game Counter: The index of your flips. Ensures that even if you make identical bets with identical seeds, the mathematical output is completely different.",
  keccak256:
    "The Cryptographic Blender (Hash): The secure formula that mixes all variables above. If the resulting hash is even, you get Heads (0). If odd, Tails (1).",
};

/** A variable name with a glowing (?) and a neon hover tooltip explaining it simply. */
function VarTip({ label }: { label: keyof typeof TIPS }) {
  const tip = TIPS[label];
  const ci = tip.indexOf(":");
  const lead = ci > -1 ? tip.slice(0, ci) : "";
  const rest = ci > -1 ? tip.slice(ci + 1) : tip;
  return (
    <span className="group relative inline-flex items-center gap-1">
      <span className="text-emerald-400/80">{label}</span>
      <span className="inline-flex h-3.5 w-3.5 cursor-help items-center justify-center rounded-full border border-emerald-400/40 text-[8px] font-bold text-emerald-300 shadow-[0_0_6px_rgba(52,211,153,0.55)]">
        ?
      </span>
      <span
        role="tooltip"
        className="pointer-events-none absolute bottom-full left-0 z-40 mb-2 w-64 max-w-[80vw] translate-y-1 rounded-lg border border-emerald-400/30 bg-slate-950/95 p-2.5 font-sans text-[11px] font-normal leading-snug tracking-normal text-white/80 opacity-0 shadow-[0_0_26px_-6px_rgba(52,211,153,0.65)] backdrop-blur transition-all duration-200 group-hover:translate-y-0 group-hover:opacity-100"
      >
        {lead && <b className="text-emerald-300">{lead}: </b>}
        {rest.trim()}
      </span>
    </span>
  );
}

function Line({ label, v }: { label: keyof typeof TIPS; v: string }) {
  return (
    <div className="break-all py-1.5 leading-relaxed">
      <VarTip label={label} />
      <span className="text-white/30"> = </span>
      <span className="text-cyan-200/80">{v}</span>
    </div>
  );
}

export default function VerifyPanel({ game }: { game: GameRow }) {
  const { network } = useWallet();
  const { hash, result } = useMemo(
    () => recomputeResult(game.prevrandao, game.player, game.seed, game.nonce),
    [game]
  );
  const matches = result === game.result;
  const explorer = network?.explorer;

  return (
    <div className="glass">
      {/* terminal header */}
      <div className="flex items-center justify-between rounded-t-2xl border-b border-white/10 bg-black/30 px-4 py-2.5">
        <div className="flex items-center gap-2">
          <span className="flex gap-1.5">
            <span className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
            <span className="h-2.5 w-2.5 rounded-full bg-amber-400/80" />
            <span className="h-2.5 w-2.5 rounded-full bg-emerald-400/80" />
          </span>
          <span className="ml-1 font-mono text-xs text-white/40">verify.sh — provably fair</span>
        </div>
        <span
          className={`rounded-md px-2.5 py-1 font-mono text-xs font-bold ${
            matches
              ? "bg-emerald-400/15 text-emerald-300 shadow-[0_0_16px_-2px_rgba(52,211,153,0.9)]"
              : "bg-red-500/15 text-red-400"
          }`}
        >
          {matches ? "✓ VERIFIED" : "✗ MISMATCH"}
        </span>
      </div>

      <div className="rounded-b-2xl bg-black/20 px-4 py-3 font-mono text-xs">
        <div className="mb-2 text-white/35">
          <span className="text-white/25"># </span>
          recomputed in your browser from public on-chain data
          <span className="ml-1 text-white/25">· hover the </span>
          <span className="text-emerald-300/80">(?)</span>
          <span className="text-white/25"> to learn what each value means</span>
        </div>
        <div className="mb-3 text-white/50">
          result = <span className="text-cyan-300">keccak256(prevrandao, player, seed, nonce) % 2</span>
        </div>

        <Line label="prevrandao" v={game.prevrandao.toString()} />
        <Line label="player" v={game.player} />
        <Line label="seed" v={game.seed} />
        <Line label="nonce" v={game.nonce.toString()} />
        <Line label="keccak256" v={hash} />

        <div className="mt-3 grid grid-cols-2 gap-3">
          <div className="rounded-lg border border-white/10 bg-slate-950/60 p-2.5 text-center">
            <div className="text-[10px] uppercase tracking-wider text-white/35">recomputed</div>
            <div className="text-sm font-bold text-emerald-300">{sideLabel(result)}</div>
          </div>
          <div className="rounded-lg border border-white/10 bg-slate-950/60 p-2.5 text-center">
            <div className="text-[10px] uppercase tracking-wider text-white/35">on-chain</div>
            <div className="text-sm font-bold text-cyan-300">{sideLabel(game.result)}</div>
          </div>
        </div>

        {explorer ? (
          <a
            href={`${explorer}/tx/${game.txHash}`}
            target="_blank"
            rel="noreferrer"
            className="mt-3 block text-center text-cyan-400 hover:underline"
          >
            view transaction on etherscan ↗
          </a>
        ) : (
          <div className="mt-3 break-all text-center text-white/35">tx: {game.txHash}</div>
        )}
      </div>
    </div>
  );
}
